{
    "ErrorBoundary.errorOccured": "发生了意想不到的错误。"
}